### ISSUE TITLE
person_detection example does not work on idf v6.0

### ISSUE THREAD

**Issue by cantorek** [espressif/esp-tflite-micro#125]
### Checklist

- [x] Checked the issue tracker for similar issues to ensure this is not a duplicate
- [x] Read the documentation to confirm the issue is not addressed there and your configuration is set correctly
- [x] Tested with the latest version to ensure the issue hasn't been fixed

### How often does this bug occurs?

always

### Expected behavior

Example would build

### Actual behavior (suspected bug)

```
Added proper directory to PATH
Activated virtual environment at /Users/canto/.espressif/tools/python/v6.0/venv
Environment setup complete for the current shell session.
These changes will be lost when you close this terminal.
You are now using IDF version 6.0.
eim select v6.0
```

bulding...

```
/Users/canto/work/turret/esp-tflite-micro/examples/person_detection/managed_components/espressif__esp32-camera/driver/esp_camera.c:21:10: fatal error: driver/gpio.h: No such file or directory
   21 | #include "driver/gpio.h"
      |          ^~~~~~~~~~~~~~~
compilation terminated.
[12/153] Building CXX object esp-idf/espressif__esp32-camera/CMakeFiles/__idf_espressif__esp32-camera.dir/conversions/jpge.cpp.obj
ninja: build stopped: subcommand failed.
Compilation failed because esp_camera.h (in "espressif__esp32-camera" component) includes driver/ledc.h, provided by esp_driver_ledc component(s).
However, esp_driver_ledc component(s) is not in the requirements list of "espressif__esp32-camera".
To fix this, add esp_driver_ledc to REQUIRES list of idf_component_register call in /Users/canto/work/turret/esp-tflite-micro/examples/person_detection/managed_components/espressif__esp32-camera/CMakeLists.txt.
```

after adding the `esp_driver_ledc`

```
/Users/canto/work/turret/esp-tflite-micro/examples/person_detection/managed_components/espressif__esp32-camera/driver/esp_camera.c:21:10: fatal error: driver/gpio.h: No such file or directory
   21 | #include "driver/gpio.h"
      |          ^~~~~~~~~~~~~~~
compilation terminated.
[15/155] Building C object esp-idf/esp_driver_ledc/CMakeFiles/__idf_esp_driver_ledc.dir/src/ledc.c.obj
ninja: build stopped: subcommand failed.
Compilation failed because esp_camera.c (in "espressif__esp32-camera" component) includes driver/gpio.h, provided by esp_driver_gpio component(s).
However, esp_driver_gpio component(s) is not in the requirements list of "espressif__esp32-camera".
To fix this, add esp_driver_gpio to PRIV_REQUIRES list of idf_component_register call in /Users/canto/work/turret/esp-tflite-micro/examples/person_detection/managed_components/espressif__esp32-camera/CMakeLists.txt.
```

and after adding `esp_driver_gpio` to `managed_components/espressif__esp32-camera/CMakeLists.txt`

```
/Users/canto/work/turret/esp-tflite-micro/examples/person_detection/managed_components/espressif__esp32-camera/target/esp32/ll_cam.c:24:37: error: unknown type name 'gpio_dev_t'
   24 | static inline int gpio_ll_get_level(gpio_dev_t *hw, int gpio_num)
      |                                     ^~~~~~~~~~
/Users/canto/work/turret/esp-tflite-micro/examples/person_detection/managed_components/espressif__esp32-camera/target/esp32/ll_cam.c: In function 'll_cam_vsync_isr':
/Users/canto/work/turret/esp-tflite-micro/examples/person_detection/managed_components/espressif__esp32-camera/target/esp32/ll_cam.c:213:9: error: implicit declaration of function 'gpio_ll_get_level' [-Wimplicit-function-declaration]
  213 |     if (gpio_ll_get_level(&GPIO, cam->vsync_pin) == !cam->vsync_invert) {
      |         ^~~~~~~~~~~~~~~~~
/Users/canto/work/turret/esp-tflite-micro/examples/person_detection/managed_components/espressif__esp32-camera/target/esp32/ll_cam.c:213:28: error: 'GPIO' undeclared (first use in this function)
  213 |     if (gpio_ll_get_level(&GPIO, cam->vsync_pin) == !cam->vsync_invert) {
      |                            ^~~~
/Users/canto/work/turret/esp-tflite-micro/examples/person_detection/managed_components/espressif__esp32-camera/target/esp32/ll_cam.c:213:28: note: each undeclared identifier is reported only once for each function it appears in
/Users/canto/work/turret/esp-tflite-micro/examples/person_detection/managed_components/espressif__esp32-camera/target/esp32/ll_cam.c: In function 'll_cam_deinit':
/Users/canto/work/turret/esp-tflite-micro/examples/person_detection/managed_components/espressif__esp32-camera/target/esp32/ll_cam.c:254:5: error: implicit declaration of function 'gpio_isr_handler_remove' [-Wimplicit-function-declaration]
  254 |     gpio_isr_handler_remove(cam->vsync_pin);
      |     ^~~~~~~~~~~~~~~~~~~~~~~
/Users/canto/work/turret/esp-tflite-micro/examples/person_detection/managed_components/espressif__esp32-camera/target/esp32/ll_cam.c: In function 'll_cam_vsync_intr_enable':
/Users/canto/work/turret/esp-tflite-micro/examples/person_detection/managed_components/espressif__esp32-camera/target/esp32/ll_cam.c:334:9: error: implicit declaration of function 'gpio_intr_enable'; did you mean 'esp_intr_enable'? [-Wimplicit-function-declaration]
  334 |         gpio_intr_enable(cam->vsync_pin);
      |         ^~~~~~~~~~~~~~~~
      |         esp_intr_enable
/Users/canto/work/turret/esp-tflite-micro/examples/person_detection/managed_components/espressif__esp32-camera/target/esp32/ll_cam.c:336:9: error: implicit declaration of function 'gpio_intr_disable'; did you mean 'esp_intr_disable'? [-Wimplicit-function-declaration]
  336 |         gpio_intr_disable(cam->vsync_pin);
      |         ^~~~~~~~~~~~~~~~~
      |         esp_intr_disable
/Users/canto/work/turret/esp-tflite-micro/examples/person_detection/managed_components/espressif__esp32-camera/target/esp32/ll_cam.c: In function 'll_cam_set_pin':
/Users/canto/work/turret/esp-tflite-micro/examples/person_detection/managed_components/espressif__esp32-camera/target/esp32/ll_cam.c:342:5: error: unknown type name 'gpio_config_t'; did you mean 'esp_log_config_t'?
  342 |     gpio_config_t io_conf = {0};
      |     ^~~~~~~~~~~~~
      |     esp_log_config_t
/Users/canto/work/turret/esp-tflite-micro/examples/person_detection/managed_components/espressif__esp32-camera/target/esp32/ll_cam.c:343:12: error: request for member 'intr_type' in something not a structure or union
  343 |     io_conf.intr_type = cam->vsync_invert ? GPIO_PIN_INTR_NEGEDGE : GPIO_PIN_INTR_POSEDGE;
      |            ^
/Users/canto/work/turret/esp-tflite-micro/examples/person_detection/managed_components/espressif__esp32-camera/target/esp32/ll_cam.c:43:31: error: 'GPIO_INTR_NEGEDGE' undeclared (first use in this function); did you mean 'GPIO_PIN_INTR_NEGEDGE'?
   43 | #define GPIO_PIN_INTR_NEGEDGE GPIO_INTR_NEGEDGE
      |                               ^~~~~~~~~~~~~~~~~
/Users/canto/work/turret/esp-tflite-micro/examples/person_detection/managed_components/espressif__esp32-camera/target/esp32/ll_cam.c:343:45: note: in expansion of macro 'GPIO_PIN_INTR_NEGEDGE'
  343 |     io_conf.intr_type = cam->vsync_invert ? GPIO_PIN_INTR_NEGEDGE : GPIO_PIN_INTR_POSEDGE;
      |                                             ^~~~~~~~~~~~~~~~~~~~~
/Users/canto/work/turret/esp-tflite-micro/examples/person_detection/managed_components/espressif__esp32-camera/target/esp32/ll_cam.c:42:31: error: 'GPIO_INTR_POSEDGE' undeclared (first use in this function); did you mean 'GPIO_PIN_INTR_POSEDGE'?
   42 | #define GPIO_PIN_INTR_POSEDGE GPIO_INTR_POSEDGE
      |                               ^~~~~~~~~~~~~~~~~
/Users/canto/work/turret/esp-tflite-micro/examples/person_detection/managed_components/espressif__esp32-camera/target/esp32/ll_cam.c:343:69: note: in expansion of macro 'GPIO_PIN_INTR_POSEDGE'
  343 |     io_conf.intr_type = cam->vsync_invert ? GPIO_PIN_INTR_NEGEDGE : GPIO_PIN_INTR_POSEDGE;
      |                                                                     ^~~~~~~~~~~~~~~~~~~~~
/Users/canto/work/turret/esp-tflite-micro/examples/person_detection/managed_components/espressif__esp32-camera/target/esp32/ll_cam.c:344:12: error: request for member 'pin_bit_mask' in something not a structure or union
  344 |     io_conf.pin_bit_mask = 1ULL << config->pin_vsync;
      |            ^
/Users/canto/work/turret/esp-tflite-micro/examples/person_detection/managed_components/espressif__esp32-camera/target/esp32/ll_cam.c:345:12: error: request for member 'mode' in something not a structure or union
  345 |     io_conf.mode = GPIO_MODE_INPUT;
      |            ^
/Users/canto/work/turret/esp-tflite-micro/examples/person_detection/managed_components/espressif__esp32-camera/target/esp32/ll_cam.c:345:20: error: 'GPIO_MODE_INPUT' undeclared (first use in this function)
  345 |     io_conf.mode = GPIO_MODE_INPUT;
      |                    ^~~~~~~~~~~~~~~
/Users/canto/work/turret/esp-tflite-micro/examples/person_detection/managed_components/espressif__esp32-camera/target/esp32/ll_cam.c:346:12: error: request for member 'pull_up_en' in something not a structure or union
  346 |     io_conf.pull_up_en = 1;
      |            ^
/Users/canto/work/turret/esp-tflite-micro/examples/person_detection/managed_components/espressif__esp32-camera/target/esp32/ll_cam.c:347:12: error: request for member 'pull_down_en' in something not a structure or union
  347 |     io_conf.pull_down_en = 0;
      |            ^
/Users/canto/work/turret/esp-tflite-micro/examples/person_detection/managed_components/espressif__esp32-camera/target/esp32/ll_cam.c:348:5: error: implicit declaration of function 'gpio_config' [-Wimplicit-function-declaration]
  348 |     gpio_config(&io_conf);
      |     ^~~~~~~~~~~
/Users/canto/work/turret/esp-tflite-micro/examples/person_detection/managed_components/espressif__esp32-camera/target/esp32/ll_cam.c:349:5: error: implicit declaration of function 'gpio_install_isr_service' [-Wimplicit-function-declaration]
  349 |     gpio_install_isr_service(ESP_INTR_FLAG_LOWMED | ESP_INTR_FLAG_IRAM);
      |     ^~~~~~~~~~~~~~~~~~~~~~~~
/Users/canto/work/turret/esp-tflite-micro/examples/person_detection/managed_components/espressif__esp32-camera/target/esp32/ll_cam.c:350:5: error: implicit declaration of function 'gpio_isr_handler_add' [-Wimplicit-function-declaration]
  350 |     gpio_isr_handler_add(config->pin_vsync, ll_cam_vsync_isr, cam);
      |     ^~~~~~~~~~~~~~~~~~~~
/Users/canto/work/turret/esp-tflite-micro/examples/person_detection/managed_components/espressif__esp32-camera/target/esp32/ll_cam.c:353:5: error: implicit declaration of function 'PIN_FUNC_SELECT' [-Wimplicit-function-declaration]
  353 |     PIN_FUNC_SELECT(GPIO_PIN_MUX_REG[config->pin_pclk], PIN_FUNC_GPIO);
      |     ^~~~~~~~~~~~~~~
/Users/canto/work/turret/esp-tflite-micro/examples/person_detection/managed_components/espressif__esp32-camera/target/esp32/ll_cam.c:353:57: error: 'PIN_FUNC_GPIO' undeclared (first use in this function)
  353 |     PIN_FUNC_SELECT(GPIO_PIN_MUX_REG[config->pin_pclk], PIN_FUNC_GPIO);
      |                                                         ^~~~~~~~~~~~~
/Users/canto/work/turret/esp-tflite-micro/examples/person_detection/managed_components/espressif__esp32-camera/target/esp32/ll_cam.c:354:5: error: implicit declaration of function 'gpio_set_direction' [-Wimplicit-function-declaration]
  354 |     gpio_set_direction(config->pin_pclk, GPIO_MODE_INPUT);
      |     ^~~~~~~~~~~~~~~~~~
/Users/canto/work/turret/esp-tflite-micro/examples/person_detection/managed_components/espressif__esp32-camera/target/esp32/ll_cam.c:355:5: error: implicit declaration of function 'gpio_set_pull_mode' [-Wimplicit-function-declaration]
  355 |     gpio_set_pull_mode(config->pin_pclk, GPIO_FLOATING);
      |     ^~~~~~~~~~~~~~~~~~
/Users/canto/work/turret/esp-tflite-micro/examples/person_detection/managed_components/espressif__esp32-camera/target/esp32/ll_cam.c:355:42: error: 'GPIO_FLOATING' undeclared (first use in this function)
  355 |     gpio_set_pull_mode(config->pin_pclk, GPIO_FLOATING);
      |                                          ^~~~~~~~~~~~~
/Users/canto/work/turret/esp-tflite-micro/examples/person_detection/managed_components/espressif__esp32-camera/target/esp32/ll_cam.c:44:31: error: implicit declaration of function 'esp_rom_gpio_connect_in_signal' [-Wimplicit-function-declaration]
   44 | #define gpio_matrix_in(a,b,c) esp_rom_gpio_connect_in_signal(a,b,c)
      |                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/canto/work/turret/esp-tflite-micro/examples/person_detection/managed_components/espressif__esp32-camera/target/esp32/ll_cam.c:356:5: note: in expansion of macro 'gpio_matrix_in'
  356 |     gpio_matrix_in(config->pin_pclk, I2S0I_WS_IN_IDX, false);
      |     ^~~~~~~~~~~~~~
/Users/canto/work/turret/esp-tflite-micro/examples/person_detection/managed_components/espressif__esp32-camera/target/esp32/ll_cam.c:356:38: error: 'I2S0I_WS_IN_IDX' undeclared (first use in this function)
  356 |     gpio_matrix_in(config->pin_pclk, I2S0I_WS_IN_IDX, false);
      |                                      ^~~~~~~~~~~~~~~
/Users/canto/work/turret/esp-tflite-micro/examples/person_detection/managed_components/espressif__esp32-camera/target/esp32/ll_cam.c:44:64: note: in definition of macro 'gpio_matrix_in'
   44 | #define gpio_matrix_in(a,b,c) esp_rom_gpio_connect_in_signal(a,b,c)
      |                                                                ^
/Users/canto/work/turret/esp-tflite-micro/examples/person_detection/managed_components/espressif__esp32-camera/target/esp32/ll_cam.c:361:39: error: 'I2S0I_V_SYNC_IDX' undeclared (first use in this function)
  361 |     gpio_matrix_in(config->pin_vsync, I2S0I_V_SYNC_IDX, false);
      |                                       ^~~~~~~~~~~~~~~~
/Users/canto/work/turret/esp-tflite-micro/examples/person_detection/managed_components/espressif__esp32-camera/target/esp32/ll_cam.c:44:64: note: in definition of macro 'gpio_matrix_in'
   44 | #define gpio_matrix_in(a,b,c) esp_rom_gpio_connect_in_signal(a,b,c)
      |                                                                ^
/Users/canto/work/turret/esp-tflite-micro/examples/person_detection/managed_components/espressif__esp32-camera/target/esp32/ll_cam.c:366:38: error: 'I2S0I_H_SYNC_IDX' undeclared (first use in this function)
  366 |     gpio_matrix_in(config->pin_href, I2S0I_H_SYNC_IDX, false);
      |                                      ^~~~~~~~~~~~~~~~
/Users/canto/work/turret/esp-tflite-micro/examples/person_detection/managed_components/espressif__esp32-camera/target/esp32/ll_cam.c:44:64: note: in definition of macro 'gpio_matrix_in'
   44 | #define gpio_matrix_in(a,b,c) esp_rom_gpio_connect_in_signal(a,b,c)
      |                                                                ^
/Users/canto/work/turret/esp-tflite-micro/examples/person_detection/managed_components/espressif__esp32-camera/target/esp32/ll_cam.c:375:38: error: 'I2S0I_DATA_IN0_IDX' undeclared (first use in this function)
  375 |         gpio_matrix_in(data_pins[i], I2S0I_DATA_IN0_IDX + i, false);
      |                                      ^~~~~~~~~~~~~~~~~~
/Users/canto/work/turret/esp-tflite-micro/examples/person_detection/managed_components/espressif__esp32-camera/target/esp32/ll_cam.c:44:64: note: in definition of macro 'gpio_matrix_in'
   44 | #define gpio_matrix_in(a,b,c) esp_rom_gpio_connect_in_signal(a,b,c)
      |                                                                ^
/Users/canto/work/turret/esp-tflite-micro/examples/person_detection/managed_components/espressif__esp32-camera/target/esp32/ll_cam.c:378:26: error: 'I2S0I_H_ENABLE_IDX' undeclared (first use in this function)
  378 |     gpio_matrix_in(0x38, I2S0I_H_ENABLE_IDX, false);
      |                          ^~~~~~~~~~~~~~~~~~
/Users/canto/work/turret/esp-tflite-micro/examples/person_detection/managed_components/espressif__esp32-camera/target/esp32/ll_cam.c:44:64: note: in definition of macro 'gpio_matrix_in'
   44 | #define gpio_matrix_in(a,b,c) esp_rom_gpio_connect_in_signal(a,b,c)
      |                                                                ^
[36/153] Building C object esp-idf/esp_driver_dac/CMakeFiles/__idf_esp_driver_dac.dir/dac_continuous.c.obj
ninja: build stopped: subcommand failed.
BUG: component_requirements.py: cannot match original component filename for source component espressif__esp32-camera
ninja failed with exit code 1, output of the command is in the /Users/canto/work/turret/esp-tflite-micro/examples/person_detection/build/log/idf_py_stderr_output_61687 and /Users/canto/work/turret/esp-tflite-micro/examples/person_detection/build/log/idf_py_stdout_output_61687
```

### Error logs or terminal output

```shell

```

### Steps to reproduce the behavior

Follow the README.md to install idf - latest - which is v6.0 - will be installed.
Try to build `person_detection` example

### Project release version

latest

### System architecture

ARM 64-bit (Apple M1/M2, Raspberry Pi 4/5)

### Operating system

MacOS

### Operating system version

sonoma

### Shell

Bash

**Comment by vikramdattu** [comment]
Dear @cantorek the esp-tflite-micro library and examples are not been updated to work with the latest IDF release v6.0.
This is taken into account and be released soon. For now, you may continue using on IDF release/v5.5.

**Comment by droman42** [comment]
A datapoint from testing the registry release against IDF **v6.0.2** (esp32s3, xtensa gcc 15.2.0):

`espressif/esp-tflite-micro==1.3.7` **core builds and links cleanly on v6.0.2** in a minimal project exercising:
- the TFLM core — `MicroInterpreter` + `MicroMutableOpResolver`, an int8 micro_speech-scale model invoke, and
- the full signal-library path — the micro_speech audio-preprocessor op set (Window / FftAutoScale / Rfft / Energy / FilterBank* / PCAN), so the `signal/` sources and kissfft wrappers all compile and link.

No errors; the only diagnostics are pre-existing `-Wshadow` warnings in `tensorflow/lite/kernels/internal/reference/{mul,sub}.h`. The app image links at ~370 KB. We did **not** test the camera-based examples (person_detection etc.), where the reported breakage lives — so this narrows the v6 gap to the examples layer, at least for esp32s3.

One small find along the way: the 1.3.7 registry distribution no longer contains `tensorflow/lite/experimental/microfrontend/` (removed upstream a while back), but the component `CMakeLists.txt` still GLOBs `${tflite_dir}/experimental/microfrontend/lib` — a vestigial no-op now.

Hope this helps.
